# Generated by Django 3.2.12 on 2022-02-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='drfuser',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='drfuser',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='drfuser',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
